### PR TITLE
Add Submit a talk proposal form

### LINKED ISSUE #38: Make "How to apply to speak?" instructions more welcoming?
On our PC call today it was brought up some speakers when contacted have been unsure what they are expected to submit after reading the instructions, and have asked for examples.

This is the current text on our workshop page:

>If your experience or expertise in the field has provided you with insights (questions or answers) about this intersection, in particular about the topics in scope of the workshop, please contact the Program Committee before July 3rd, 2020 and we will work with you in confirming and defining your proposed contribution.

https://www.w3.org/2020/06/machine-learning-workshop/speakers.html#submit

This may sound the bar for submitting a proposal is high ("provided you with insights") and concrete instructions on the expected submission are lacking ("please contact the Program Committee").

I suggest we make this text more welcoming and be more liberal in what we accept as a proposal. And maybe provide an example. I was thinking a web form that asks the right questions might encourage more responses, but integrating that into static GH pages hosting might not be feasible.

Suggestions welcome!

Cc @dontcallmedom @kdavis-mozilla @huningxin

### PR DESCRIPTION
**Pull request by anssiko**
Uses "subject" and "body" header fields per
https://tools.ietf.org/html/rfc6068

Fix #38

### CODE REVIEW

**Comment by anssiko** [comment]
Staged for testing at https://anssiko.github.io/machine-learning-workshop/speakers.html

**Comment by anssiko** [comment]
@dontcallmedom JS factored into its own file so translations needed only for the HTML content in speakers.html.

**Comment by huningxin** [comment]
Looks good to me. Thanks @anssiko .

**Comment by anssiko** [comment]
Thanks @huningxin!

Given the deadline to submit talks is [this Friday](https://www.w3.org/2020/06/machine-learning-workshop/#dates), I'll deploy this form now.

@dontcallmedom if you have comments or suggestions, feel free to submit another PR. I leave it to W3C Staff to handle speakers.html translations to Chinese and Japanese.

**Pull request merged**
