### PR TITLE
add an interpreter instruction pointer in Chinese presentation page

### PR DESCRIPTION
**Pull request by ruoxiran**

### CODE REVIEW

**Review by dontcallmedom — APPROVED** [review]

**Comment by xfq** [comment]
This should probably be added to the English version as well. If someone asks a question in Chinese, I think the English speakers also need to turn on the interpreter function in Zoom.

**Comment by ruoxiran** [comment]
> This should probably be added to the English version as well. If someone asks a question in Chinese, I think the English speakers also need to turn on the interpreter function in Zoom.

Our current plan is to provide simultaneous interpretation only for Chinese participants, in case English participants get confused. If Chinese participants have questions, I will help them translate the questions to the public channel. 

> This should probably be added to the English version as well. If someone asks a question in Chinese, I think the English speakers also need to turn on the interpreter function in Zoom.

Our current plan is to provide simultaneous interpretation only for Chinese participants, in case English participants get confused. If Chinese participants have questions, I will help them translate the questions to the public channel. 
Fuqiao, would you also like to help translate the question during the meeting?  In case I don't get their point.

**Comment by ruoxiran** [comment]
> This should probably be added to the English version as well. If someone asks a question in Chinese, I think the English speakers also need to turn on the interpreter function in Zoom.

Our current plan is to provide simultaneous interpretation only for Chinese participants, in case English participants get confused. If Chinese participants have questions, I will help them translate the questions to the public channel.
Fuqiao, would you also like to help translate the question during the meeting? In case I don't get their point.

**Comment by xfq** [comment]
> > This should probably be added to the English version as well. If someone asks a question in Chinese, I think the English speakers also need to turn on the interpreter function in Zoom.
> 
> Our current plan is to provide simultaneous interpretation only for Chinese participants, in case English participants get confused. If Chinese participants have questions, I will help them translate the questions to the public channel.

I see. Thank you.

> Fuqiao, would you also like to help translate the question during the meeting? In case I don't get their point.

If I'm able to participate (i.e., no conflict meetings), I will.

**Pull request merged**
